plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  
collections:
  catalog:
    output: true

social:
  name: Porolonych
  links:
    - https://www.facebook.com/porolonych
    - https://www.instagram.com/porolonych/

logo: /images/logo.jpg
url: https://porolonych.ru

title: ""
lang: "ru_RU"

defaults:
  -
    scope:
      path: ""
    values:
      image: /images/logo.jpg
